//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductHeader", Namespace="http://schemas.datacontract.org/2004/07/Ch07_Networking.Recipe7_1.ProductsDataSoa" +
        "pService")]
    public partial class ProductHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> ListPriceField;
        
        private string NameField;
        
        private System.Nullable<ushort> ProductIdField;
        
        private string SellEndDateField;
        
        private string SellStartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ListPrice {
            get {
                return this.ListPriceField;
            }
            set {
                if ((this.ListPriceField.Equals(value) != true)) {
                    this.ListPriceField = value;
                    this.RaisePropertyChanged("ListPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ushort> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellEndDate {
            get {
                return this.SellEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SellEndDateField, value) != true)) {
                    this.SellEndDateField = value;
                    this.RaisePropertyChanged("SellEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellStartDate {
            get {
                return this.SellStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SellStartDateField, value) != true)) {
                    this.SellStartDateField = value;
                    this.RaisePropertyChanged("SellStartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDetail", Namespace="http://schemas.datacontract.org/2004/07/Ch07_Networking.Recipe7_1.ProductsDataSoa" +
        "pService")]
    public partial class ProductDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ClassField;
        
        private string ColorField;
        
        private System.Nullable<byte> DaysToManufactureField;
        
        private string DiscontinuedDateField;
        
        private string FinishedGoodsFlagField;
        
        private string MakeFlagField;
        
        private System.Nullable<ushort> ProductIdField;
        
        private string ProductLineField;
        
        private string ProductNumberField;
        
        private System.Nullable<ushort> ReorderPointField;
        
        private System.Nullable<ushort> SafetyStockLevelField;
        
        private string SizeField;
        
        private System.Nullable<decimal> StandardCostField;
        
        private string StyleField;
        
        private string WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DaysToManufacture {
            get {
                return this.DaysToManufactureField;
            }
            set {
                if ((this.DaysToManufactureField.Equals(value) != true)) {
                    this.DaysToManufactureField = value;
                    this.RaisePropertyChanged("DaysToManufacture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscontinuedDate {
            get {
                return this.DiscontinuedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscontinuedDateField, value) != true)) {
                    this.DiscontinuedDateField = value;
                    this.RaisePropertyChanged("DiscontinuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinishedGoodsFlag {
            get {
                return this.FinishedGoodsFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FinishedGoodsFlagField, value) != true)) {
                    this.FinishedGoodsFlagField = value;
                    this.RaisePropertyChanged("FinishedGoodsFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeFlag {
            get {
                return this.MakeFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeFlagField, value) != true)) {
                    this.MakeFlagField = value;
                    this.RaisePropertyChanged("MakeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ushort> ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductLine {
            get {
                return this.ProductLineField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductLineField, value) != true)) {
                    this.ProductLineField = value;
                    this.RaisePropertyChanged("ProductLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNumber {
            get {
                return this.ProductNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNumberField, value) != true)) {
                    this.ProductNumberField = value;
                    this.RaisePropertyChanged("ProductNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ushort> ReorderPoint {
            get {
                return this.ReorderPointField;
            }
            set {
                if ((this.ReorderPointField.Equals(value) != true)) {
                    this.ReorderPointField = value;
                    this.RaisePropertyChanged("ReorderPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ushort> SafetyStockLevel {
            get {
                return this.SafetyStockLevelField;
            }
            set {
                if ((this.SafetyStockLevelField.Equals(value) != true)) {
                    this.SafetyStockLevelField = value;
                    this.RaisePropertyChanged("SafetyStockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StandardCost {
            get {
                return this.StandardCostField;
            }
            set {
                if ((this.StandardCostField.Equals(value) != true)) {
                    this.StandardCostField = value;
                    this.RaisePropertyChanged("StandardCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Style {
            get {
                return this.StyleField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleField, value) != true)) {
                    this.StyleField = value;
                    this.RaisePropertyChanged("Style");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.ServiceModel.ServiceContractAttribute()]
    public interface IProductManager {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetProductHeaders", ReplyAction="http://tempuri.org/IProductManager/GetProductHeadersResponse")]
        System.IAsyncResult BeginGetProductHeaders(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> EndGetProductHeaders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/UpdateProductHeaders", ReplyAction="http://tempuri.org/IProductManager/UpdateProductHeadersResponse")]
        System.IAsyncResult BeginUpdateProductHeaders(System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateProductHeaders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/GetProductDetail", ReplyAction="http://tempuri.org/IProductManager/GetProductDetailResponse")]
        System.IAsyncResult BeginGetProductDetail(ushort ProductId, System.AsyncCallback callback, object asyncState);
        
        Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail EndGetProductDetail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProductManager/UpdateProductDetail", ReplyAction="http://tempuri.org/IProductManager/UpdateProductDetailResponse")]
        System.IAsyncResult BeginUpdateProductDetail(Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update, System.AsyncCallback callback, object asyncState);
        
        void EndUpdateProductDetail(System.IAsyncResult result);
    }
    
    public interface IProductManagerChannel : Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class GetProductHeadersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductHeadersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class GetProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class ProductManagerClient : System.ServiceModel.ClientBase<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager>, Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager {
        
        private BeginOperationDelegate onBeginGetProductHeadersDelegate;
        
        private EndOperationDelegate onEndGetProductHeadersDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductHeadersCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateProductHeadersDelegate;
        
        private EndOperationDelegate onEndUpdateProductHeadersDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateProductHeadersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductDetailDelegate;
        
        private EndOperationDelegate onEndGetProductDetailDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductDetailCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateProductDetailDelegate;
        
        private EndOperationDelegate onEndUpdateProductDetailDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateProductDetailCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductManagerClient() {
        }
        
        public ProductManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetProductHeadersCompletedEventArgs> GetProductHeadersCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateProductHeadersCompleted;
        
        public event System.EventHandler<GetProductDetailCompletedEventArgs> GetProductDetailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpdateProductDetailCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        System.IAsyncResult Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.BeginGetProductHeaders(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductHeaders(callback, asyncState);
        }
        
        System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.EndGetProductHeaders(System.IAsyncResult result) {
            return base.Channel.EndGetProductHeaders(result);
        }
        
        private System.IAsyncResult OnBeginGetProductHeaders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).BeginGetProductHeaders(callback, asyncState);
        }
        
        private object[] OnEndGetProductHeaders(System.IAsyncResult result) {
            System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> retVal = ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).EndGetProductHeaders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductHeadersCompleted(object state) {
            if ((this.GetProductHeadersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductHeadersCompleted(this, new GetProductHeadersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductHeadersAsync() {
            this.GetProductHeadersAsync(null);
        }
        
        public void GetProductHeadersAsync(object userState) {
            if ((this.onBeginGetProductHeadersDelegate == null)) {
                this.onBeginGetProductHeadersDelegate = new BeginOperationDelegate(this.OnBeginGetProductHeaders);
            }
            if ((this.onEndGetProductHeadersDelegate == null)) {
                this.onEndGetProductHeadersDelegate = new EndOperationDelegate(this.OnEndGetProductHeaders);
            }
            if ((this.onGetProductHeadersCompletedDelegate == null)) {
                this.onGetProductHeadersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductHeadersCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductHeadersDelegate, null, this.onEndGetProductHeadersDelegate, this.onGetProductHeadersCompletedDelegate, userState);
        }
        
        System.IAsyncResult Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.BeginUpdateProductHeaders(System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateProductHeaders(Updates, callback, asyncState);
        }
        
        void Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.EndUpdateProductHeaders(System.IAsyncResult result) {
            base.Channel.EndUpdateProductHeaders(result);
        }
        
        private System.IAsyncResult OnBeginUpdateProductHeaders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates = ((System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader>)(inValues[0]));
            return ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).BeginUpdateProductHeaders(Updates, callback, asyncState);
        }
        
        private object[] OnEndUpdateProductHeaders(System.IAsyncResult result) {
            ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).EndUpdateProductHeaders(result);
            return null;
        }
        
        private void OnUpdateProductHeadersCompleted(object state) {
            if ((this.UpdateProductHeadersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateProductHeadersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateProductHeadersAsync(System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates) {
            this.UpdateProductHeadersAsync(Updates, null);
        }
        
        public void UpdateProductHeadersAsync(System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates, object userState) {
            if ((this.onBeginUpdateProductHeadersDelegate == null)) {
                this.onBeginUpdateProductHeadersDelegate = new BeginOperationDelegate(this.OnBeginUpdateProductHeaders);
            }
            if ((this.onEndUpdateProductHeadersDelegate == null)) {
                this.onEndUpdateProductHeadersDelegate = new EndOperationDelegate(this.OnEndUpdateProductHeaders);
            }
            if ((this.onUpdateProductHeadersCompletedDelegate == null)) {
                this.onUpdateProductHeadersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateProductHeadersCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateProductHeadersDelegate, new object[] {
                        Updates}, this.onEndUpdateProductHeadersDelegate, this.onUpdateProductHeadersCompletedDelegate, userState);
        }
        
        System.IAsyncResult Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.BeginGetProductDetail(ushort ProductId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductDetail(ProductId, callback, asyncState);
        }
        
        Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.EndGetProductDetail(System.IAsyncResult result) {
            return base.Channel.EndGetProductDetail(result);
        }
        
        private System.IAsyncResult OnBeginGetProductDetail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ushort ProductId = ((ushort)(inValues[0]));
            return ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).BeginGetProductDetail(ProductId, callback, asyncState);
        }
        
        private object[] OnEndGetProductDetail(System.IAsyncResult result) {
            Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail retVal = ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).EndGetProductDetail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductDetailCompleted(object state) {
            if ((this.GetProductDetailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductDetailCompleted(this, new GetProductDetailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductDetailAsync(ushort ProductId) {
            this.GetProductDetailAsync(ProductId, null);
        }
        
        public void GetProductDetailAsync(ushort ProductId, object userState) {
            if ((this.onBeginGetProductDetailDelegate == null)) {
                this.onBeginGetProductDetailDelegate = new BeginOperationDelegate(this.OnBeginGetProductDetail);
            }
            if ((this.onEndGetProductDetailDelegate == null)) {
                this.onEndGetProductDetailDelegate = new EndOperationDelegate(this.OnEndGetProductDetail);
            }
            if ((this.onGetProductDetailCompletedDelegate == null)) {
                this.onGetProductDetailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductDetailCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductDetailDelegate, new object[] {
                        ProductId}, this.onEndGetProductDetailDelegate, this.onGetProductDetailCompletedDelegate, userState);
        }
        
        System.IAsyncResult Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.BeginUpdateProductDetail(Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateProductDetail(Update, callback, asyncState);
        }
        
        void Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager.EndUpdateProductDetail(System.IAsyncResult result) {
            base.Channel.EndUpdateProductDetail(result);
        }
        
        private System.IAsyncResult OnBeginUpdateProductDetail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update = ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail)(inValues[0]));
            return ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).BeginUpdateProductDetail(Update, callback, asyncState);
        }
        
        private object[] OnEndUpdateProductDetail(System.IAsyncResult result) {
            ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager)(this)).EndUpdateProductDetail(result);
            return null;
        }
        
        private void OnUpdateProductDetailCompleted(object state) {
            if ((this.UpdateProductDetailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateProductDetailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateProductDetailAsync(Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update) {
            this.UpdateProductDetailAsync(Update, null);
        }
        
        public void UpdateProductDetailAsync(Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update, object userState) {
            if ((this.onBeginUpdateProductDetailDelegate == null)) {
                this.onBeginUpdateProductDetailDelegate = new BeginOperationDelegate(this.OnBeginUpdateProductDetail);
            }
            if ((this.onEndUpdateProductDetailDelegate == null)) {
                this.onEndUpdateProductDetailDelegate = new EndOperationDelegate(this.OnEndUpdateProductDetail);
            }
            if ((this.onUpdateProductDetailCompletedDelegate == null)) {
                this.onUpdateProductDetailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateProductDetailCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateProductDetailDelegate, new object[] {
                        Update}, this.onEndUpdateProductDetailDelegate, this.onUpdateProductDetailCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager CreateChannel() {
            return new ProductManagerClientChannel(this);
        }
        
        private class ProductManagerClientChannel : ChannelBase<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager>, Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager {
            
            public ProductManagerClientChannel(System.ServiceModel.ClientBase<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.IProductManager> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProductHeaders(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProductHeaders", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> EndGetProductHeaders(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> _result = ((System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader>)(base.EndInvoke("GetProductHeaders", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateProductHeaders(System.Collections.Generic.List<Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductHeader> Updates, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Updates;
                System.IAsyncResult _result = base.BeginInvoke("UpdateProductHeaders", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateProductHeaders(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateProductHeaders", _args, result);
            }
            
            public System.IAsyncResult BeginGetProductDetail(ushort ProductId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ProductId;
                System.IAsyncResult _result = base.BeginInvoke("GetProductDetail", _args, callback, asyncState);
                return _result;
            }
            
            public Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail EndGetProductDetail(System.IAsyncResult result) {
                object[] _args = new object[0];
                Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail _result = ((Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail)(base.EndInvoke("GetProductDetail", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateProductDetail(Ch07_Networking.Recipe7_1.ProductsDataViewer.ProductsDataSoapService.ProductDetail Update, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Update;
                System.IAsyncResult _result = base.BeginInvoke("UpdateProductDetail", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUpdateProductDetail(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("UpdateProductDetail", _args, result);
            }
        }
    }
}
